from _typeshed import Incomplete

POLICY: Incomplete

def module(name): ...
def run_hook(payload, tmp_path, table): ...
def seen(workspace, sid): ...
def test_patch_checks_every_file_and_reconstructs_content(tmp_path) -> None: ...
def test_patch_delete_move_eof_and_sequential_hunks(tmp_path) -> None: ...
def test_bad_patch_is_refused_without_mutation(tmp_path) -> None: ...
def test_real_first_line_gate_blocks_patch_even_on_second_file(tmp_path) -> None: ...
def test_shell_read_is_recorded_only_after_success(tmp_path) -> None: ...
def test_shell_context_read_does_not_deadlock_and_then_unlocks(tmp_path) -> None: ...
def test_search_redirect_and_running_commands_are_not_fabricated_reads(tmp_path) -> None: ...
def test_unrelated_tool_is_silent(tmp_path) -> None: ...
def test_real_size_gate_sees_complete_patch_result(tmp_path) -> None: ...
def test_rtk_success_unlocks_context_with_relative_workdir(tmp_path) -> None: ...
def test_a_failed_patch_does_not_run_the_post_edit_pipeline(tmp_path) -> None: ...
def test_ambiguous_shell_results_do_not_record_reads(tmp_path) -> None: ...
def test_native_stdout_only_read_unlocks_context(tmp_path, command) -> None: ...
def test_native_stdout_requires_complete_unambiguous_read(tmp_path) -> None: ...
def test_generator_progress_does_not_enter_model_context(tmp_path, monkeypatch, capsys): ...
