def crop(path, shade, mark=None): ...
def test_the_same_image_on_many_pages_is_one_decorative_figure(tmp_path) -> None: ...
def test_an_image_on_one_page_of_a_short_pdf_is_content(tmp_path) -> None: ...
def test_a_repeat_links_to_its_first_appearance_and_is_not_described_again(tmp_path) -> None: ...
def test_coverage_counts_each_word_as_often_as_the_reference_has_it() -> None: ...
def test_text_layer_is_judged_page_by_page() -> None: ...
