WORDS: str

def make_pdf(path, text=...): ...
def fake_engine(page_md=..., figures: int = 1): ...
def said(image, describer, ocr_text): ...
def build(pdf, **kw): ...
def offline(monkeypatch): ...
def test_the_frontmatter_names_the_source_the_hash_and_the_audit(tmp_path) -> None: ...
def test_a_fresh_twin_is_skipped_and_a_changed_pdf_is_rebuilt(tmp_path) -> None: ...
def test_a_lost_page_or_word_flags_the_twin_for_review(tmp_path) -> None: ...
def test_no_origin_versions_small_previews_and_keeps_originals_local(tmp_path) -> None: ...
def test_a_live_origin_keeps_every_image_out_of_git(tmp_path) -> None: ...
def test_a_secret_in_the_text_gitignores_the_whole_twin(tmp_path) -> None: ...
def test_both_engines_write_the_same_twin_but_for_the_engine_line(tmp_path) -> None: ...
def test_a_missing_engine_venv_hands_back_the_install_command(tmp_path, monkeypatch) -> None: ...
