def locate(lines: list[str], wanted: list[str], start: int, eof: bool = False) -> int: ...
def updated(content: str, body: list[str]) -> str: ...
def changes(command: str, cwd: str, after: bool = False) -> list[dict]: ...
