from _typeshed import Incomplete

HERE: Incomplete

def shell_commands(command: str) -> list[list[str]]: ...
def read_command(parts: list[str]) -> list[str]: ...
def shell_reads(command: str, cwd: str) -> list[dict]: ...
def succeeded(raw: dict) -> bool: ...
def invoke(raw: dict, rel: str, messages: list[str]) -> int: ...
def translated(raw: dict, tool: str, data: dict) -> dict: ...
def main() -> int: ...
