from _typeshed import Incomplete

MODELO: Incomplete
LABELS: Incomplete
INLINE: Incomplete
BLOCK: Incomplete

def uniq_cells(row): ...
def match_label(text): ...
def extract(source, name): ...
def set_font(run, name: str = 'Times New Roman') -> None: ...
def fill(fields, out) -> None: ...
