from _typeshed import Incomplete
from pathlib import Path

HERE: Incomplete

def table_path() -> Path: ...
def load_table() -> dict[str, list[tuple[str, str]]]: ...
def run_gate(rel: str) -> tuple[int, str, str]: ...
def emit(messages: list[str]) -> None: ...
def collect(text: str, messages: list[str]) -> None: ...
def main() -> int: ...
