from _typeshed import Incomplete
from pathlib import Path

HERE: Incomplete
LIMITS_FILE: Incomplete
VENDORED_FILE: Incomplete
GENERATED_FILE: Incomplete
EXTENSIONLESS_FILE: Incomplete
CODE_EXTS: Incomplete
GENERATED: Incomplete
FACADES: Incomplete
EXAMPLE_COMMENT: Incomplete

def is_tool_entrypoint(path: Path) -> bool: ...
def is_code_file(path: Path) -> bool: ...
def load_limits() -> dict: ...
def allowed_extensionless() -> set: ...
def is_vendored(path: Path, root: Path) -> bool: ...
def is_generated_artifact(path: Path, root: Path) -> bool: ...
def is_authored(path: Path, root: Path) -> bool: ...
def over_column_cap(text: str, cols: int) -> list: ...
def is_authored_prose(path: Path, root: Path) -> bool: ...
def main() -> int: ...
