from typing import Any

def parse_stdin() -> tuple[dict[str, Any], str, dict[str, Any], str, str]: ...
def is_subagent(raw: dict[str, Any]) -> bool: ...
def normalise(raw: str) -> str: ...
def seen_file(session_id: str) -> str: ...
def load_seen(session_id: str) -> set[str]: ...
def mark_seen(session_id: str, path: str) -> None: ...
def iface_seen_file(session_id: str) -> str: ...
def load_iface_seen(session_id: str) -> set[str]: ...
def mark_iface_seen(session_id: str, path: str) -> None: ...
