from pre_commit import git as git

def prepare(commit) -> None: ...
def routing(commit) -> None: ...
def issues(commit) -> None: ...
def interfaces(commit) -> None: ...
def skills(commit) -> None: ...
