from _typeshed import Incomplete

P: str
A: str
R: str
MC: str
P14: str
P159: str
DIM: float
EASE: Incomplete

def q(ns, tag): ...
def transition(slide, kind: str = 'morph', dur: int = 1000, direction: str = 'l', after=None, by: str = 'Object') -> None: ...
def morph_key(shape, key: str): ...
def appear(shape, **kw): ...
def fade_in(shape, dur: int = 400, **kw): ...
def fade_out(shape, dur: int = 300, **kw): ...
def wipe_in(shape, dur: int = 600, direction: str = 'left', **kw): ...
def grow(shape, pct, dur: int = 600, **kw): ...
def spin(shape, deg, dur: int = 800, **kw): ...
def move(shape, path: str, dur: int = 800, **kw): ...
def dim(shape, to=..., **kw): ...
def timeline(slide, clicks, triggers=None, auto_first: bool = False): ...
def link(shape, target): ...
