from _typeshed import Incomplete

W: Incomplete
H: Incomplete
M: int
FOOT_H: int
FOOT_Y: Incomplete
TYPE: Incomplete

def section(spec, p): ...
def split(spec, p): ...
def content(spec, p): ...
def statement(spec, p): ...
def number(spec, p): ...
def quote(spec, p): ...
def definition(spec, p): ...
def image(spec, p): ...
def compare(spec, p): ...
def canvas(spec, p): ...
def code(spec, p): ...
def cover(spec, p): ...

KINDS: Incomplete

def build(spec: dict) -> list[tuple[str, str]]: ...
