import pathlib
from _typeshed import Incomplete

SCOPES: Incomplete
SCOPES_WRITE: Incomplete
SLIDE_W: Incomplete
SLIDE_H: Incomplete

def get_service(alias: str, write: bool = False): ...
def get_presentation(alias: str, presentation_id: str, write: bool = False) -> dict: ...
def list_presentations(alias: str, name: str = '') -> list: ...
def create(alias: str, title: str) -> dict: ...
def apply(alias: str, presentation_id: str, requests: list) -> dict: ...
def url(presentation_id: str) -> str: ...
def textbox(object_id: str, page_id: str, text: str, x: float = 0.1, y: float = 0.1, w: float = 0.8, h: float = 0.15) -> list: ...
def move(object_id: str, x: float, y: float) -> dict: ...
def previews(alias: str, presentation_id: str, out_dir: pathlib.Path, dpi: int = 100) -> list: ...
def contact_sheets(paths: list, out_dir: pathlib.Path, cols: int = 5, rows: int = 4) -> list: ...
