from _typeshed import Incomplete

SLUG: str
SECTION: Incomplete

def test_a_slug_id_is_a_valid_id(tmp_path) -> None: ...
def test_a_slug_spec_satisfies_its_slug_across_the_notation_seam(tmp_path) -> None: ...
def test_a_numeric_spec_does_not_pay_a_slugs_debt(tmp_path) -> None: ...
