from _typeshed import Incomplete

CONTEXT_GATE: Incomplete
PRE_READ: Incomplete

def test_both_read_gates_name_the_same_complete_set() -> None: ...
def test_a_satisfied_read_costs_no_further_round_trip() -> None: ...
def test_a_stub_is_demanded_of_a_read_and_of_nothing_else() -> None: ...
def test_the_python_reading_of_a_stub_matches_the_shell_gates(state, expected_rc, marker, tmp_path) -> None: ...
