from collections import Counter
from pathlib import Path

def name_of(value: str) -> str: ...
def identity(session: str = '', agent: str = '') -> tuple[str, str]: ...
def records(path: Path): ...
def transcript(session: str, agent: str, cwd: Path, given: str = '') -> Path | None: ...
def patch_lines(text: str) -> Counter: ...
def successful(output) -> bool: ...
def edits(path: Path, cwd: Path) -> Counter: ...
def repository(path: Path) -> Path | None: ...
def choose(root: Path, cwd: Path, session: str, agent: str, log: Path | None) -> dict: ...
def publish(info: dict, text: str | None) -> None: ...
