from _typeshed import Incomplete
from pathlib import Path

MAP: str
HEAD: Incomplete

def declared(root: Path) -> set: ...
def link(url: str) -> str: ...
def home(folder: Path) -> str: ...
def known(text: str) -> dict: ...
def redraw(root: Path, leave_dirty: bool) -> str: ...
