from _typeshed import Incomplete

pptx: Incomplete

def test_an_entrance_animates_the_whole_shape_not_only_its_label() -> None: ...
def test_timing_ids_are_unique_across_clicks_and_triggers() -> None: ...
def test_a_move_and_a_scale_on_one_click_with_different_durations_is_flagged() -> None: ...
def test_a_move_over_a_third_of_the_slide_is_flagged() -> None: ...
def test_a_morph_with_nothing_paired_is_flagged_and_a_named_pair_is_not() -> None: ...
def test_flatten_gives_one_page_per_click_in_order_with_each_state() -> None: ...
def test_a_back_link_returns_to_the_slide_the_talk_came_from() -> None: ...
