from _typeshed import Incomplete

pptx: Incomplete
SPEC: Incomplete

def test_each_section_is_a_master_with_every_layout_in_spec_order() -> None: ...
def test_each_master_theme_holds_its_own_section_colour_and_its_text_colour() -> None: ...
def test_master_and_layout_ids_are_unique_and_in_the_reserved_range() -> None: ...
def test_no_layout_hardcodes_a_colour_so_one_layout_serves_every_section() -> None: ...
def test_text_never_shrinks_to_fit() -> None: ...
def test_a_split_names_its_colour_side_and_fills_that_share_of_the_slide() -> None: ...
def test_a_preview_sample_exists_for_every_layout_and_every_section_colour() -> None: ...
