OCR: str

def backends(**answers): ...
def test_overlap_counts_the_ocr_words_the_description_kept() -> None: ...
def test_too_little_ocr_cannot_judge_so_any_answer_passes() -> None: ...
def test_an_invented_description_escalates_to_the_next_describer() -> None: ...
def test_a_failing_or_empty_describer_is_skipped_not_raised() -> None: ...
def test_when_every_describer_fails_the_check_the_best_is_kept_and_flagged() -> None: ...
def test_nothing_at_all_is_an_empty_flagged_description() -> None: ...
def test_video_frames_go_through_the_shared_describer(monkeypatch): ...
