from _typeshed import Incomplete

GOAL_A: str
GOAL_B: str

def test_load_goals_parses_header(tmp_path) -> None: ...
def test_load_goals_strips_auto_blocks_and_urls(tmp_path) -> None: ...
def test_load_goals_skips_non_goal_files(tmp_path) -> None: ...
def test_load_goals_missing_dir_is_empty() -> None: ...

class FakeEncoder:
    table: Incomplete
    seen: Incomplete
    def __init__(self, table) -> None: ...
    def __call__(self, texts): ...

def test_relevance_ranks_closest_goal_first() -> None: ...
def test_relevance_margin_is_relative_to_mean() -> None: ...
def test_relevance_applies_e5_prefixes() -> None: ...
def test_relevance_top_n_truncates() -> None: ...
def test_relevance_empty_text_returns_empty() -> None: ...
def test_relevance_no_goals_returns_empty() -> None: ...
def test_format_matches_handles_empty() -> None: ...
def test_format_matches_one_line_per_match() -> None: ...
