from _typeshed import Incomplete
from pathlib import Path

STUB_FOR: Incomplete
GATE_ON: Incomplete

def interface_for(path): ...
def stub_out_dir(path) -> Path: ...
def find_stubgen(): ...
def emit_pyi(path) -> bool: ...
def emit_dts(path, tsc) -> bool: ...
def find_tsc(): ...
def main() -> int: ...
