from _typeshed import Incomplete

W: Incomplete
H: Incomplete
FONT: str
GRAY: str
LIGHT: str
MID: str
ACCENT: str

def rgb(hexa): ...
def frame(page, x, y, w, h): ...
def style_reqs(oid, st): ...
def element(page, oid, el): ...
def clone_elements(page, sid, src): ...
def placeholder_text(src, ptype): ...
def build(deck, insercoes, prefix): ...
def notes(deck, made): ...
