from _typeshed import Incomplete

GRAY: Incomplete
LIGHT: Incomplete
MID: Incomplete
ACCENT: Incomplete
WHITE: Incomplete
OLD: Incomplete

def titulo(pt, en=None): ...
def fonte(txt, url): ...
def legenda(txt, y: float = 0.8): ...
def tokens(lista, x: float = 0.05, y0: float = 0.3, w: float = 0.17, h: float = 0.075, dest=()): ...
def modelo(nome, sub, x: float = 0.31, y: float = 0.33, w: float = 0.2, h: float = 0.3): ...
def barras(pares, x: float = 0.6, y0: float = 0.3, h: float = 0.07, dest: int = 0): ...
def numero(n, txt, y: float = 0.32): ...
def imagem(url, x: float = 0.5, y: float = 0.25, w: float = 0.45, h: float = 0.6): ...
def desenhado(els, notas): ...
def fallback(titulo_, corpo, notas: str = ''): ...
def secao(txt, notas: str = ''): ...
def clones(*pares): ...
def vocabulario(termos, notas: str = 'Passe rápido: cada palavra numa frase, dita pela turma.'): ...
def verificacao(perguntas, notas): ...
