from _typeshed import Incomplete

DASHBOARD: Incomplete
GREEN: Incomplete
RED: Incomplete
SEEDED_ISSUES: str
PARTS: Incomplete

def test_dirty_stop_prints_the_paths_and_asks_whose(tmp_path) -> None: ...
def test_dirty_stop_does_not_assert_whose_work_it_is(tmp_path) -> None: ...
def test_leave_dirty_promotes_without_touching_the_tree(tmp_path) -> None: ...
def test_leave_dirty_never_commits_the_foreign_dirt(tmp_path) -> None: ...
def test_clean_tree_still_commits_entropy(tmp_path) -> None: ...
def test_the_two_blocks_and_the_hand_written_issues_coexist(tmp_path) -> None: ...
def test_a_red_suite_reports_itself_in_the_verify_block(tmp_path) -> None: ...
def test_a_real_merge_is_refused_while_the_tree_is_not_ours(tmp_path) -> None: ...
def test_red_verify_blocks_promotion(tmp_path) -> None: ...
def test_no_promote_needs_a_reason(tmp_path) -> None: ...
def test_unknown_flag_is_a_usage_error(tmp_path) -> None: ...
def test_the_flags_compose(tmp_path) -> None: ...
