from _typeshed import Incomplete

handoff: Incomplete

def repo(path): ...
def log(path, rows): ...
def patch(call, name, lines, success: bool = True): ...
def test_same_pair_shares_latest_handoff_and_old_session_cannot_clear_it(tmp_path) -> None: ...
def test_different_environments_and_repositories_have_distinct_paths(tmp_path) -> None: ...
def test_ranking_counts_only_successful_session_edits(tmp_path) -> None: ...
def test_claude_errors_and_sidechains_are_excluded(tmp_path): ...
def test_no_recorded_edits_falls_back_without_inspecting_dirty_diff(tmp_path) -> None: ...
def test_identity_is_not_guessed_from_latest_session(monkeypatch) -> None: ...
def test_name_follows_the_selected_repository_without_session_suffix(tmp_path) -> None: ...
def test_lock_refuses_concurrent_publication_and_clear_preserves_unknown_owner(tmp_path) -> None: ...
