import pytest

IGNORED: str
SEED: str

@pytest.fixture
def repomap(): ...
def test_a_row_this_clone_cannot_confirm_survives_the_redraw(tmp_path, repomap) -> None: ...
def test_a_cloned_project_gets_its_remote_and_its_drive_home(tmp_path, repomap) -> None: ...
def test_a_folder_the_declaration_does_not_name_gets_no_row(tmp_path, repomap) -> None: ...
def test_a_second_redraw_changes_nothing(tmp_path, repomap) -> None: ...
