import pytest
from _typeshed import Incomplete

ENV: Incomplete

@pytest.fixture
def roundup(): ...
def test_a_project_ahead_of_its_remote_is_pushed(tmp_path, roundup) -> None: ...
def test_a_project_with_no_remote_is_named(tmp_path, roundup) -> None: ...
def test_a_project_already_pushed_says_nothing(tmp_path, roundup) -> None: ...
