from _typeshed import Incomplete

DONE: Incomplete
PENDING: Incomplete
DATA: Incomplete

def parse(body: str) -> list: ...
def check(panel: str, caixas, rows: list) -> list: ...
def draw(panel: str, rows: list) -> str: ...
def render(text: str) -> tuple: ...
def main() -> int: ...
