from _typeshed import Incomplete
from pathlib import Path

PDFINFO: Incomplete
TEXT_PAGE: int
WORD: Incomplete
FIELDS: Incomplete

def sha256(path: Path) -> str: ...
def pdfinfo(path: Path) -> dict: ...
def page_texts(path: Path) -> list[str]: ...
def text_layer(pages: list[str]) -> str: ...
def ocr_page(path: Path, page: int) -> str: ...
def reference(path: Path, pages: list[str]) -> str: ...
def coverage(reference_text: str, markdown: str) -> float: ...
def counts(markdown: str) -> dict: ...
def render_frontmatter(fields: dict) -> str: ...
def read_frontmatter(twin: Path) -> dict: ...
def replace_frontmatter(twin: Path, **changes) -> None: ...
