from _typeshed import Incomplete
from pathlib import Path

PDFINFO: Incomplete
TEXT_PAGE: int
WORD: Incomplete
RAW_COMMANDS: Incomplete
RAW_MODULES: Incomplete
FIELDS: Incomplete

def sha256(path: Path) -> str: ...
def twin_of(pdf: Path) -> Path: ...
def source_of(twin: Path) -> Path | None: ...
def twin_state(pdf: Path) -> tuple[str, Path]: ...
def pdfinfo(path: Path) -> dict: ...
def page_texts(path: Path) -> list[str]: ...
def text_layer(pages: list[str]) -> str: ...
def render(path: Path, prefix: Path, pages: list[int] | None = None, dpi: int = 150) -> list[Path]: ...
def images(path: Path, prefix: Path) -> list[Path]: ...
def ocr_page(path: Path, page: int) -> str: ...
def reference(path: Path, pages: list[str]) -> str: ...
def coverage(reference_text: str, markdown: str) -> float: ...
def counts(markdown: str) -> dict: ...
def render_frontmatter(fields: dict) -> str: ...
def read_frontmatter(twin: Path) -> dict: ...
def replace_frontmatter(twin: Path, **changes) -> None: ...
