from pathlib import Path

ENGINE_VENV: str
ENGINE_TIMEOUT: int
REVIEW_COVERAGE: float

class EngineMissing(RuntimeError): ...

def run_engine(engine: str, pdf: Path, out: Path) -> dict: ...
def origin_live(url: str | None) -> bool: ...
def build(pdf: Path, engine: str, describer: str = 'agy', origin: str | None = None, force: bool = False, _engine=..., _describe=..., _ocr=...) -> dict: ...
