import argparse
from _typeshed import Incomplete
from pathlib import Path

REVIEW_DPI: int
FLAGGED_PAGE: Incomplete

def parse(argv: list[str], leaf: str) -> argparse.Namespace: ...
def flagged_pages(twin: Path) -> list[int]: ...
def review(pdf: Path, leaf: str) -> str: ...
def stamp(pdf: Path, who: str) -> str: ...
def convert(pdf: Path, engine: str, args: argparse.Namespace) -> str: ...
def main(engine: str, leaf: str, argv: list[str]) -> int: ...
