from _typeshed import Incomplete

N_EQUIPES: int
FW: Incomplete
FH: Incomplete
GAP_X: Incomplete
GAP_Y: Incomplete
COLS: int
INK: str
LABEL: str
HINT: str
FILLED: str

def frame(eid, x, y, name): ...
def rect(eid, x, y, w, h, fid, stroke=..., dashed: bool = False): ...
def ellipse(eid, x, y, w, h, fid, stroke=...): ...
def text(eid, x, y, s, fid, size: int = 20, color=..., family: int = 1, w=None): ...
def bloco(els, fid, tag, x, y, label, hint, box_h, filled=None) -> None: ...
def montar_frame(els, idx, x, y, name, dados=None) -> None: ...

EXEMPLO: Incomplete

def build(): ...
