from _typeshed import Incomplete

AQUI: Incomplete
PAGINA: str
TITULO: str
ANTIGOS: Incomplete
MARCA: Incomplete

def par(texto): ...
def toggle(texto, filhos): ...
def folha(f): ...
def blocos(dado): ...
def ops(dado): ...
def main() -> None: ...
