import pathlib
from _typeshed import Incomplete

ATTACHED: Incomplete
BOT_NOISE: Incomplete

def transcript_for(audio_name: str, media: pathlib.Path) -> str | None: ...
def fold(line: str, media: pathlib.Path) -> list[str]: ...
def is_noise(line: str) -> bool: ...

FORMATTED_CPF: Incomplete
BARE_CPF: Incomplete
PASSWORD: Incomplete
CPF_LABEL: str
CPF_WINDOW: int

def redact_line(line: str, in_cpf_context: bool) -> str: ...
def redact(text: str) -> str: ...
def stitch(export: pathlib.Path, media: pathlib.Path) -> str: ...

DATE: Incomplete

def span(text: str) -> tuple[str, str]: ...
def header(who: str, text: str, audios: int) -> str: ...
def run(export: pathlib.Path, out: pathlib.Path, who: str | None = None) -> int: ...
