import pathlib

REJECTED: str

def duration(path: pathlib.Path) -> float: ...
def audios(root: pathlib.Path) -> list[pathlib.Path]: ...
def transcript_of(path: pathlib.Path) -> pathlib.Path: ...
def eta(done_audio: float, total_audio: float, elapsed: float) -> str: ...
def run(root: pathlib.Path, prompt: str, model=None) -> int: ...
