import pathlib
from _typeshed import Incomplete

SCOPES: Incomplete
EXPORT_MIME: Incomplete
FILE_FIELDS: str

def get_service(alias: str): ...
def list_files(alias: str, folder_id: str = 'root', page_size: int = 50) -> list: ...
def search_files(alias: str, query: str, page_size: int = 20) -> list: ...
def recent_files(alias: str, page_size: int = 30) -> list: ...
def download_file(alias: str, file_id: str, dest_dir: pathlib.Path) -> pathlib.Path: ...
