import pathlib
from google.oauth2.credentials import Credentials

def config_dir(service: str) -> pathlib.Path: ...
def get_accounts() -> list: ...
def primary_aliases() -> list: ...
def resolve_alias(alias: str) -> str: ...
def auth(alias: str, service: str, scopes: list) -> Credentials: ...
