import pathlib

def render_element(el: dict, slide_w: float, slide_h: float, assets_dir: pathlib.Path | None, img_n: list[int], ph_sizes: dict[str, int] = {}, ph_valign: dict[str, str] = {}, ph_weight: dict[str, int] = {}, ph_color: dict[str, str] = {}, ph_family: dict[str, str] = {}, is_master: bool = False) -> str | None: ...
