from _typeshed import Incomplete

SCOPES: Incomplete

def get_service(alias: str): ...
def get_presentation(alias: str, presentation_id: str) -> dict: ...
def list_presentations(alias: str) -> list: ...
