def text_html(text_obj: dict, is_title: bool = False, default_font_size: int | None = None, default_align: str = '', default_font_weight: int | None = None, default_font_color: str | None = None, default_font_family: str | None = None) -> str: ...
def has_content(html_str: str) -> bool: ...
