import pathlib

def render_element(el: dict, slide_w: float, slide_h: float, assets_dir: pathlib.Path | None, img_n: list[int], ph_sizes: dict[str, int] = {}, is_master: bool = False) -> str | None: ...
