from _typeshed import Incomplete

YTDLP: Incomplete
ATTACH: Incomplete
COOKIES: Incomplete

def source_of(url): ...
def probe(url, runner=None): ...
def clean_vtt(text): ...
def get_captions(url, lang: str = 'en', runner=None, workdir=None): ...
def assemble(url, level: str = 'auto', save: bool = False, base=None, _probe=None, _captions=None, _media=None): ...
