from _typeshed import Incomplete

GOALS_DIR: Incomplete
MODEL: str
MAX_CHARS: int

def load_goals(goals_dir=None): ...
def default_encoder(name=...): ...
def relevance(text, goals=None, top_n: int = 5, encoder=None): ...
def format_matches(matches): ...
