from _typeshed import Incomplete

WARN: Incomplete
CAP: Incomplete

def test_the_crowding_warning_says_it_did_not_refuse(tmp_path) -> None: ...
def test_the_crowding_refusal_says_it_refused(tmp_path) -> None: ...
def test_the_crowding_ratchet_holds_the_cap_not_the_signal() -> None: ...
def test_a_generated_block_is_not_charged_to_the_author() -> None: ...
def test_a_wholly_generated_document_counts_zero() -> None: ...
def test_size_sees_the_list_it_had_been_blind_to() -> None: ...
def test_the_name_witness_refuses_a_name_that_is_only_prose() -> None: ...
def test_the_fixed_gate_reads_the_shape_the_lists_are_really_written_in() -> None: ...
def test_the_fixed_gate_asks_for_proof_when_a_keyed_item_leaves() -> None: ...
def test_an_item_that_carries_no_id_is_not_invented_into_one() -> None: ...
def test_the_spec_this_file_is_can_be_found_by_the_id_it_answers_to() -> None: ...
