from _typeshed import Incomplete
from conftest import WORKSPACE_ROOT as WORKSPACE_ROOT

LONG: Incomplete
COLS: Incomplete

def test_an_ordinary_long_line_is_flagged() -> None: ...
def test_a_long_table_row_is_exempt() -> None: ...
def test_a_long_line_in_a_fenced_block_is_exempt() -> None: ...
def test_prose_after_a_fence_closes_is_flagged_again() -> None: ...
def test_a_long_frontmatter_line_is_exempt() -> None: ...
def test_the_exemption_covers_the_block_not_one_key() -> None: ...
def test_a_description_line_in_the_BODY_is_not_exempt() -> None: ...
def test_only_the_LEADING_block_is_frontmatter() -> None: ...
def test_an_unterminated_frontmatter_marker_exempts_nothing() -> None: ...
def test_a_line_long_only_because_of_a_url_is_exempt() -> None: ...
def test_a_relative_link_target_counts_the_same_way() -> None: ...
def test_the_authored_half_is_still_measured_at_full_width() -> None: ...
def test_a_bare_word_with_a_slash_is_not_a_link() -> None: ...
