from _typeshed import Incomplete

ROOT: Incomplete
REPOS: Incomplete
needs_repo: Incomplete

def test_every_code_repo_has_a_picture() -> None: ...
@needs_repo
def test_a_repo_page_carries_only_the_drawings_it_has_a_source_for() -> None: ...
def test_the_page_shell_still_renders_every_tab_when_given_every_panel() -> None: ...
def test_the_findings_band_reads_the_ledger_rather_than_recounting(tmp_path) -> None: ...
def test_a_repo_with_no_ledger_says_so_instead_of_guessing(tmp_path) -> None: ...
@needs_repo
def test_the_picture_is_deterministic() -> None: ...
