from _typeshed import Incomplete

def trusted_model(event: dict, model: str) -> str: ...

ROOT: Incomplete
CHARS_PER_TOKEN: float

def paths_for(project: str, session: str = '') -> list: ...
def turns(project: str, session: str = ''): ...
