from _typeshed import Incomplete
from pathlib import Path

def trusted_model(event: dict, model: str) -> str: ...

ROOT: Incomplete
CODEX_ROOT: Incomplete
CHARS_PER_TOKEN: float

def paths_for(project: str, session: str = '', provider: str = 'claude') -> list: ...
def events(path: Path): ...
def responses(path: Path, sidechain: bool = False) -> dict: ...
def turns(project: str, session: str = '', provider: str = 'claude'): ...
