from pathlib import Path as Path

def mirror(): ...
def test_suite_files_and_links_survive_relocation(tmp_path) -> None: ...
def test_disabled_suite_is_pruned_and_global_directory_is_not_duplicated(tmp_path, monkeypatch): ...
