from _typeshed import Incomplete

def trend_label(counts): ...
def build_stats_block(path): ...

DONE_RE: Incomplete

def compress_done(content, slug): ...
def append_done_log(slug, archived) -> None: ...
def load_goal_files(): ...
def staged_goal_files(goal_files): ...
def pre_commit() -> None: ...
def check_compass_reminder() -> None: ...
def main() -> None: ...
