from _typeshed import Incomplete

BRAIN: Incomplete
GOALS_FILE: Incomplete
ATTN_LOG: Incomplete
DONE_LOG: Incomplete
GOALS_DIR: Incomplete
PERIODS: Incomplete
DONE_KEEP: int

def git(*args): ...
def touch_count(path, days): ...
def last_touch_date(path): ...
def trend_label(counts): ...
def build_stats_block(path): ...
def replace_block(content, start, end, new_block): ...

DONE_RE: Incomplete

def compress_done(content, slug): ...
def append_done_log(slug, archived) -> None: ...
def bar(count, max_val, width: int = 10): ...
def area_from_file(path): ...
def timing_display(text): ...
def parse_goal_file(path): ...
def update_goals_table(goal_files) -> None: ...
def update_goals_md(goal_files) -> None: ...
def update_attention_log(commit, touched_paths) -> None: ...
def load_goal_files(): ...
def main() -> None: ...
def check_compass_reminder() -> None: ...
