from pathlib import Path
from typing import Any

def emit_allow(message: str = '') -> None: ...
def gate(script: str, payload: dict[str, Any], tool: str, root: Path, messages: list[str]) -> bool: ...
def main() -> int: ...
