from typing import Any

def parse_stdin() -> tuple[dict[str, Any], str, dict[str, Any], str, str]: ...
def seen_file(session_id: str) -> str: ...
def load_seen(session_id: str) -> set[str]: ...
def mark_seen(session_id: str, path: str) -> None: ...
