from _typeshed import Incomplete
from pathlib import Path

FIXED_RE: Incomplete

def fixed_ids(text: str) -> set[str]: ...
def repo_root(path: Path) -> Path | None: ...
def has_spec(root: Path, bug_id: str) -> bool: ...
def main() -> int: ...
