#!/usr/bin/env python3
# paper-scaffold.py: Initialize or adapt a paper directory to workspace standards.
#
# Usage:
#   paper-scaffold.py new <name>     — create Academy/papers/<name>/ from template
#   paper-scaffold.py adapt <path>   — add missing scaffold files to existing paper
#
# Both modes are safe: existing files are never overwritten (skipped with ~).

from __future__ import annotations
import sys
from pathlib import Path

PAPERS = Path(__file__).parent.parent / 'Academy' / 'papers'
RS, RE = '<!-- routing:start -->', '<!-- routing:end -->'
ROUTE = f'{RS}\n## Routing\n\n{RE}\n'


def _reviews_ctx(name: str) -> str:
    return f"""# Reviews
> Curated reference analyses for {name} — one YAML per bib entry in lib/refs.bib

## Schema

```yaml
key: <bib-key>
type: article | book | conference | preprint | thesis
year: <year>
venue: "<journal or conference>"
url: "<DOI or canonical link>"
citations: <count or "~N">
contributions:
  - <one bullet per distinct claim>
gaps:
  - <limitation relevant to this work>
tags: [<role-first>, <metric>, <method>, <platform>]
relevance: "<how this reference relates to this manuscript>"
notes: ~  # cross-paper lineage, group connections, anything cross-file
```

## Tag Categories

Tags are a flat list. Always put role tags first; add domain-specific tags after.

| Category | Values |
|----------|--------|
| **Role** (1–2, always first) | `foundational` · `survey` · `competing-work` · `baseline` · `ground-truth` · `method-source` · `tool` · `application` |
| **Domain** | ← add paper-specific domain tags here (e.g. method names, platforms, metrics) |

`baseline` = directly compared against in experiments; `competing-work` = same problem space, no direct benchmark.
Add a `## Domain Tags` section below with the specific values for this paper once the domain is clear.

Use `notes` for cross-paper prose. No need to update both files when noting a connection — write it in whichever file you are editing.

## Workflow

- Read a review before making claims about a paper in the manuscript.
- Create or update `reviews/<key>.yaml` when you add `\\cite{{key}}` to a section.
- The `post-edit` hook warns about missing review files when `lib/refs.bib` is edited.
- The hook warns when `relevance:` is empty or missing after a `.tex` save.

{ROUTE}"""


def _sections_ctx() -> str:
    return f"""# Sections
> Source files for each manuscript section (200 LOC limit per file)

**Interface enforcement:** Every `.tex` file has a `.texif` sibling (auto-generated).
Read the `.texif` before reading or editing a section — the pre-read hook enforces this.
See `LABELS.md` at the paper root for the cross-file label registry.

{ROUTE}"""


def _paper_ctx(name: str, slug: str) -> str:
    return f"""# {name}
> ← add one-line description

TODO: brief summary — contribution, target venue, status.

## Build

```bash
cd /mnt/workspace/Academy/papers/{slug}
latexmk -xelatex -halt-on-error -interaction=nonstopmode main.tex
```

Clean rebuild: `latexmk -C && latexmk -xelatex -halt-on-error -interaction=nonstopmode main.tex`

{ROUTE}"""


def _main_tex(name: str) -> str:
    return f"""% Main document: orchestration only — preamble, section inputs, bibliography.
\\documentclass{{article}}
\\usepackage{{amsmath,amssymb,graphicx,hyperref}}

\\title{{{name}}}
\\author{{TODO}}

\\begin{{document}}
\\maketitle

\\input{{sections/01_introduction}}

% \\bibliography{{lib/refs}}
\\end{{document}}
"""


_LATEXMKRC = '$pdf_mode = 5;\n$out_dir = ".";\n$aux_dir = "build";\n'
_GITIGNORE = 'build/\nmain.pdf\n*.synctex.gz\n*.fls\n*.fdb_latexmk\n*.aux\n*.log\n'
_SUB_CTX = lambda d: f'# {d.title()}\n> ← add description\n\n{ROUTE}'


def _terms_yaml() -> str:
    return """\
# terms.yaml — canonical terminology for this paper.
# Run: Core/tools/terms <paper-path>
# Each key is the CORRECT form. The list is wrong forms to flag.
# The pre-commit hook runs this scan and warns on deviations.
#
# Example:
#   real-time:
#     - real time
#     - realtime
#     - near-real-time
#
canonical: {}  # ← replace {} with your term definitions
"""


def scaffold(root: Path, name: str, slug: str, is_new: bool) -> None:
    created: list[str] = []
    skipped: list[str] = []

    def put(rel: str, content: str) -> None:
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        if p.exists():
            skipped.append(rel)
        else:
            p.write_text(content, encoding='utf-8')
            created.append(rel)

    if is_new:
        put('main.tex', _main_tex(name))
        put('.latexmkrc', _LATEXMKRC)
        put('.gitignore', _GITIGNORE)

    put('CONTEXT.md', _paper_ctx(name, slug))
    put('LABELS.md', '# LABELS — cross-file label registry\n> Auto-generated by tex-interface-gen.py — do not edit.\n')
    put('terms.yaml', _terms_yaml())
    put('sections/CONTEXT.md', _sections_ctx())
    put('reviews/CONTEXT.md', _reviews_ctx(name))
    for d in ('lib', 'images', 'tables'):
        put(f'{d}/CONTEXT.md', _SUB_CTX(d))
    put('outputs/CONTEXT.md', '# Outputs\n> Research artifacts: metrics CSVs, analysis notes, generated reports, planning docs. Do not edit manually.\n\n' + ROUTE)

    verb = 'Created' if is_new else 'Adapted'
    print(f'{verb}: {root}')
    for f in created:
        print(f'  + {f}')
    for f in skipped:
        print(f'  ~ {f} (exists — skipped)')
    if is_new:
        print(f'\nNext steps:')
        print(f'  cd {root}')
        print(f'  git init && git remote add origin <overleaf-url>')
        print(f'  git add . && git commit -m "Initial scaffold"')


def main() -> int:
    args = sys.argv[1:]
    if len(args) < 2 or args[0] not in ('new', 'adapt'):
        print('Usage:\n  paper-scaffold.py new <name>\n  paper-scaffold.py adapt <path>', file=sys.stderr)
        return 1

    if args[0] == 'new':
        slug = args[1].replace(' ', '_').lower()
        root = PAPERS / slug
        if root.exists():
            print(f'Error: {root} already exists — use "adapt" to fill missing files.', file=sys.stderr)
            return 1
        scaffold(root, args[1], slug, is_new=True)
    else:
        root = Path(args[1]).resolve()
        if not root.exists():
            print(f'Error: {root} does not exist.', file=sys.stderr)
            return 1
        scaffold(root, root.name.replace('_', ' ').title(), root.name, is_new=False)

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
