from _typeshed import Incomplete
from pathlib import Path

CODE_EXTS: Incomplete
CONTENT_EXTS: Incomplete
ALL_EXTS = CODE_EXTS | CONTENT_EXTS
SPLIT_THRESHOLD: int
PLACEHOLDER: str
COMMENT_RE: Incomplete

def file_description(path: Path) -> str: ...
def python_api(path: Path) -> list: ...
def js_api(path: Path) -> list: ...
def extract_api(path: Path) -> str: ...
def interface_for(src: Path, ctx_dir: Path) -> str: ...
def code_files(directory: Path) -> list: ...
def has_code_content(directory: Path) -> bool: ...
def subdir_scan(directory: Path, rs: str, re_end: str) -> tuple: ...
def parse_preserved_files(inner: str) -> dict: ...
def parse_preserved_subs(inner: str) -> dict: ...
def build_sub_rows(link_list: list, preserved_subs: dict) -> str: ...
def build_file_rows(files_with_rel: list, preserved: dict, ctx_dir: Path) -> str: ...
def build_routing_block(sub_content: str, file_content: str, rs: str, re_end: str) -> str: ...
