CEILING_SECONDS: float

def test_no_bash_tool_remains_under_core_tools() -> None: ...
def test_the_mirror_check_is_not_slow_again() -> None: ...
def test_the_check_does_not_spawn_a_process_per_skill() -> None: ...
