def test_a_partial_commit_does_not_gain_the_regenerated_list(tmp_path) -> None: ...
def test_without_named_only_the_fixture_does_reach_the_bug(tmp_path) -> None: ...
def test_a_full_commit_still_carries_the_regenerated_list(tmp_path) -> None: ...
def test_commit_dash_a_still_carries_the_regenerated_list(tmp_path) -> None: ...
def test_a_partial_commit_that_names_the_list_gets_it_regenerated(tmp_path) -> None: ...
def test_is_partial_reads_the_index_file_the_hook_was_handed(monkeypatch, value, expected) -> None: ...
def test_a_partial_commit_does_not_gain_the_healed_gitignore(tmp_path) -> None: ...
def test_the_issues_generator_asks_for_named_only(monkeypatch, tmp_path): ...
def test_the_brain_dashboard_asks_for_named_only(monkeypatch, tmp_path): ...
