from _typeshed import Incomplete

SEAM: str
MACHINE_PATH_CEILING: int
VENV_POSIX_CEILING: int
RECORDS: Incomplete
LAUNCHER: str

def test_no_per_os_script_sits_beside_the_python() -> None: ...
def test_only_the_seam_knows_what_an_os_is() -> None: ...
def test_a_path_that_becomes_data_is_spelled_by_the_seam() -> None: ...
def test_no_setup_shard_is_named_for_an_operating_system() -> None: ...
def test_a_machine_path_does_not_spread() -> None: ...
def test_a_posix_only_venv_path_does_not_spread() -> None: ...
def test_the_launcher_is_the_only_thing_that_cannot_ask() -> None: ...
def test_no_shell_hook_spawns_the_bare_word_python3() -> None: ...
def test_no_document_teaches_a_tool_call_that_cannot_run() -> None: ...
