from _typeshed import Incomplete

CORE: Incomplete
HOOKS: Incomplete
SHIMS: Incomplete

def test_every_shim_names_at_least_one_canonical_script() -> None: ...
def test_opencode_spawns_only_scripts_that_exist() -> None: ...
def test_copilot_spawns_only_scripts_that_exist() -> None: ...
def test_zcode_spawns_only_scripts_that_exist() -> None: ...
def test_claude_spawns_only_scripts_that_exist() -> None: ...
def test_antigravity_spawns_only_scripts_that_exist() -> None: ...
def test_the_launcher_every_shim_goes_through_is_there() -> None: ...
