from _typeshed import Incomplete

HEAD_WARN: Incomplete
FINISHED_CEILING: int
UNDESCRIBED_CEILING: int
MISPLACED_CEILING: int
FINISHED_SLACK: int
UNDESCRIBED_SLACK: int
MISPLACED_SLACK: int

def test_prose_describing_finished_work_does_not_grow() -> None: ...
def test_unanswered_placeholders_do_not_grow() -> None: ...
def test_constraints_in_context_heads_do_not_grow() -> None: ...
def test_the_ceilings_are_not_stale() -> None: ...

MACHINE_PATH_CEILING: int
VENV_POSIX_CEILING: int
SEAM: str
LAUNCHER: str

def test_no_per_os_script_sits_beside_the_python() -> None: ...
def test_only_the_seam_knows_what_an_os_is() -> None: ...
def test_a_path_that_becomes_data_is_spelled_by_the_seam() -> None: ...
def test_no_setup_shard_is_named_for_an_operating_system() -> None: ...
def test_a_machine_path_does_not_spread() -> None: ...
def test_a_posix_only_venv_path_does_not_spread() -> None: ...
