from _typeshed import Incomplete

DAY: Incomplete

def test_a_day_and_the_same_day_a_year_later_share_one_column() -> None: ...
def test_a_read_lands_in_the_column_of_the_day_it_happened(tmp_path) -> None: ...
def test_a_column_a_year_stale_is_cleared_before_it_is_believed(tmp_path) -> None: ...
def test_a_range_is_a_sum_of_columns_and_nothing_is_stored_per_range(tmp_path) -> None: ...
def test_a_file_nothing_read_all_year_loses_its_row(tmp_path) -> None: ...
def test_the_hook_only_ever_appends(tmp_path) -> None: ...
def test_folding_twice_does_not_count_a_read_twice(tmp_path) -> None: ...
