import pytest
from _typeshed import Incomplete

GATE: Incomplete
TRACKER: Incomplete

@pytest.fixture
def session(): ...
def test_a_fresh_twin_blocks_the_pdf_until_the_twin_is_read(tmp_path, session) -> None: ...
def test_no_fresh_twin_is_refused_with_the_command_that_makes_it(tmp_path, session, state) -> None: ...
def test_a_raw_reader_in_the_shell_gets_the_same_verdict(tmp_path, session, command) -> None: ...
def test_a_command_that_only_names_a_pdf_passes(tmp_path, session, command) -> None: ...
def test_a_subagent_is_gated_too_and_handed_only_the_twin(tmp_path, session) -> None: ...
