from _typeshed import Incomplete

reflow_tool: Incomplete

def test_a_wrapped_sentence_becomes_one_line() -> None: ...
def test_a_field_separator_survives() -> None: ...
def test_a_hard_break_ends_a_backlog_item() -> None: ...
def test_two_bullets_never_fuse() -> None: ...
def test_an_indented_continuation_joins_its_bullet() -> None: ...
def test_a_fence_and_a_generated_block_are_untouched() -> None: ...
def test_frontmatter_is_untouched() -> None: ...
def test_the_header_block_is_untouched() -> None: ...
def test_a_table_is_untouched() -> None: ...
def test_the_round_trip_loses_no_word() -> None: ...
