def test_no_ledger_assigns_a_model() -> None: ...
def test_a_bolded_model_assignment_is_a_finding(tmp_path) -> None: ...
def test_a_tier_assignment_passes(tmp_path) -> None: ...
def test_a_model_name_as_DATA_passes(tmp_path) -> None: ...
def test_a_part_is_a_ledger_too(tmp_path) -> None: ...
def test_a_file_that_is_not_a_ledger_is_not_asked(tmp_path) -> None: ...
def test_an_exempt_path_may_name_the_shape_it_forbids(tmp_path) -> None: ...
