def test_no_retired_token_survives() -> None: ...
def test_the_law_may_name_what_it_retires(tmp_path) -> None: ...
def test_retired_token_in_a_filename_is_a_hit(tmp_path) -> None: ...
def test_an_inflection_of_a_retired_token_is_a_hit(tmp_path) -> None: ...
def test_an_accented_letter_is_part_of_the_word(tmp_path) -> None: ...
def test_a_retired_token_inside_a_url_is_not_a_hit(tmp_path) -> None: ...
def test_a_vendored_file_is_not_policed() -> None: ...
def test_the_line_number_survives_a_blanked_url(tmp_path) -> None: ...
