from _typeshed import Incomplete
from pathlib import Path

PDF_PATH: Incomplete
SEGMENT: Incomplete
HEREDOC: Incomplete
LEAF_TEXT: Incomplete

def reads_raw(command: str, pm) -> bool: ...
def pdfs_in(command: str, cwd: str) -> list[Path]: ...
def refuse(pdf: Path, state: str, twin: Path, needed: list[Path]) -> None: ...
def main() -> int: ...
