import datetime
from _typeshed import Incomplete
from pathlib import Path

WINDOW: int
EVENTS: Incomplete
MATRIX: Incomplete
HEADER: str

def column(day: datetime.date) -> int: ...
def enabled() -> bool: ...
def record(path: str, store: Path = None) -> None: ...
def load(matrix: Path = None) -> tuple: ...
def fold(events: Path = None, matrix: Path = None, today: datetime.date = None) -> dict: ...
def write(rows: dict, today: datetime.date, matrix: Path = None) -> None: ...
def span(rows: dict, days: int, today: datetime.date = None) -> list: ...
