import pathlib
from _typeshed import Incomplete

HERE: Incomplete
MAP: Incomplete
HEADER: Incomplete

def base() -> str: ...

SLUG_RE: Incomplete
PRIVATE: Incomplete

class Refused(Exception): ...

def load(path: pathlib.Path = ...) -> list[dict]: ...
def preamble(path: pathlib.Path = ...) -> list[str]: ...
def save(rows: list[dict], path: pathlib.Path = ...) -> None: ...
def validate_slug(slug: str) -> None: ...
def check_private(slug: str, home: str = '') -> None: ...
def add(slug: str, url: str, owner: str = '', home: str = '', path: pathlib.Path = ...) -> dict: ...
def remove(slug: str, path: pathlib.Path = ...) -> dict: ...
def find(term: str, path: pathlib.Path = ...) -> list[dict]: ...
def redirects(rows: list[dict], code: int = 302) -> str: ...
def check(rows: list[dict]) -> list[str]: ...
