import pathlib
from _typeshed import Incomplete

ROOT: Incomplete
CLASSES: Incomplete
GENERATORS: Incomplete
PRIVATE: Incomplete

class Refused(Exception): ...

def mirror_of(page: pathlib.Path, publish: pathlib.Path, classes: pathlib.Path = ...) -> pathlib.Path: ...
def redraw(page: pathlib.Path) -> list[str]: ...
def mirror(page: pathlib.Path, publish: pathlib.Path, classes: pathlib.Path = ...) -> list[pathlib.Path]: ...
def push(publish: pathlib.Path, paths: list, message: str) -> None: ...
