from _typeshed import Incomplete

HOOKS: Incomplete

def test_session_state_lives_in_a_directory_the_workspace_owns() -> None: ...
def test_asking_for_a_marker_is_enough_to_be_able_to_write_it() -> None: ...
def test_per_machine_state_never_reaches_git() -> None: ...
def test_no_hook_builds_session_state_out_of_the_system_temp_directory() -> None: ...
