def test_the_install_command_is_answered_on_whatever_machine_this_is() -> None: ...
def test_one_dependency_name_serves_every_package_manager() -> None: ...
def test_the_interpreter_is_the_one_already_running() -> None: ...
def test_a_path_that_became_data_never_carries_a_backslash() -> None: ...
def test_every_shell_hook_parses_including_the_ones_with_no_extension() -> None: ...
def test_a_repo_is_a_git_dir_with_a_head_or_a_git_file(tmp_path) -> None: ...
def test_no_hook_tests_for_a_repo_by_whether_dot_git_exists() -> None: ...
