from _typeshed import Incomplete

FILES: Incomplete

def test_the_ledger_the_scatter_writes_gets_committed(tmp_path) -> None: ...
def test_an_unchanged_ledger_is_not_committed_again(tmp_path) -> None: ...
def test_a_repo_mid_operation_is_left_alone(tmp_path) -> None: ...
def test_staged_work_in_the_repo_stays_staged(tmp_path) -> None: ...
